M48
; DRILL file {KiCad 9.0.5} date 2025-11-06T15:37:34+0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-06T15:37:34+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X90.5Y-38.5
X90.5Y-105.0
X167.0Y-38.5
X167.5Y-105.5
M30
